version: "3.7"
services:
  database:
    container_name: animal_db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./database:/database
    restart: always

volumes:
  database:
