version: "3.7"
services:
  database:
    container_name: animal_db
    image: mongo:latest
    ports:
      - '27018:27018'
    volumes:
      - ./database:/database
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: none

volumes:
  database:
